### ISSUE TITLE
Accessing class members when assigned to Interactor.userData breaks on flash target

### ISSUE THREAD

**Issue by matrefeytontias** [deltaluca/nape#91]
Example, this works on every target:
```Haxe
body = new Body(BodyType.DYNAMIC);
body.userData.gravity = new Vec2(0, 10);
trace(body.userData.gravity.get_angle());
```
And this crashes only on Flash:
```Haxe
body = new Body(BodyType.DYNAMIC);
body.userData.gravity = new Vec2(0, 10);
trace(body.userData.gravity.angle);
```

**Comment by deltaluca** [comment]
Man, I need to figure out how to get github to filter better, only just saw this now.

This issue is not to do with Nape, but the semantics of property access on Dynamic objects, since userData is completely untyped userData.gravity is also untyped so property access works differently and must be done through Reflect.getProperty I believe.

Of course, the simpler way is to tell compiler what the (known to you) type is like:
````(body.userData.gravity : Vec2).angle````

**Comment by matrefeytontias** [comment]
Alright then, I'll do that, thanks :)
